using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.OleDb;

namespace LandReg2023
{
    public partial class EmployeeNewAccount : Form
    {
        public string ConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\ICT_PROJECT\C# Land Reg\LandReg2023\LandReg2023db.accdb";
        OleDbConnection connection = new OleDbConnection();
        string imageLocation = "";
        public EmployeeNewAccount()
        {
            InitializeComponent();
            connection.ConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=D:\ICT_PROJECT\C# Land Reg\LandReg2023\LandReg2023db.accdb";

//Provider=Microsoft.ACE.OLEDB.12.0;Data 
//Source=G:\ICT_PROJECT\C# Land Reg\LandReg2023\LandReg2023db.accdb;Persist Security Info=False;";
        }

        private void btnUpload_Click(object sender, EventArgs e)
        {
            try
            {
                OpenFileDialog dialog = new OpenFileDialog();
                dialog.Filter = "jpg files(.*jpg)|*.jpg| PNG files(.*png)|*.png| All Files(*.*)|*.*";

                if (dialog.ShowDialog() == System.Windows.Forms.DialogResult.OK)
                {
                    imageLocation = dialog.FileName;
                    pictureBox1.ImageLocation = imageLocation;

                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            bool verifyId = false;
            try {
                if (string.IsNullOrEmpty(txtboxEmpFname.Text) || string.IsNullOrEmpty(txtboxEmpLname.Text) || string.IsNullOrEmpty(txtboxEmpAddress.Text) ||
                    string.IsNullOrEmpty(txtboxEmpbirthdate.Text) || string.IsNullOrEmpty(txtboxEmpEmail.Text) || string.IsNullOrEmpty(txtboxEmpContactnum.Text) ||
                    string.IsNullOrEmpty(txtboxEmpNic.Text) || string.IsNullOrEmpty(txtBoxEmp_ID.Text) || string.IsNullOrEmpty(txtBoxEmpPass.Text))
                {
                    MessageBox.Show("please enter required fields");
                }
                else
                {
                    string gender = "";
                    if (radiobtnMale.Checked)
                    {
                        gender = "male";
                    }
                    else
                    {
                        gender = "Female";
                    }


                    //Getting User Id from the database before inserting values (The Employee ID does not generated by the
                    //NewAccount Interface - its already there in the databse. only Employee details are inserting)
                    
                        //user id

                        //insert emp_details into database to reference to that Emp_ID given by the department
                        connection.Open();
                        OleDbCommand command1 = new OleDbCommand();
                        command1.Connection = connection;
                        command1.CommandText = ("UPDATE Employees SET First_Name=@fname, Last_Name=@lname, Address=@address, Date_of_birth=@birthdate," +
                            "Gender=@geneder, Email=@email, Contact_Number=@telnum, NIC_Number=@nicnum, Digital_photo=@photo WHERE Emp_ID=@id;");


                        command1.Parameters.AddWithValue("@fname", txtboxEmpFname.Text);
                        command1.Parameters.AddWithValue("@lname", txtboxEmpLname.Text);
                        command1.Parameters.AddWithValue("@address", txtboxEmpAddress.Text);
                        command1.Parameters.AddWithValue("@birthdate", txtboxEmpbirthdate.Text);
                        command1.Parameters.AddWithValue("@geneder", gender);
                        command1.Parameters.AddWithValue("@email", txtboxEmpEmail.Text);
                        command1.Parameters.AddWithValue("@telnum", txtboxEmpContactnum.Text);
                        command1.Parameters.AddWithValue("@nicnum", txtboxEmpNic.Text);
                        command1.Parameters.AddWithValue("@photo", imageLocation);
                        command1.Parameters.AddWithValue("@id", txtBoxEmp_ID.Text);
                        command1.ExecuteNonQuery();
                        MessageBox.Show("operation complete!");
                        connection.Close();


                        PersonalAccountManage accountManage = new PersonalAccountManage();

                        string password = PersonalAccountManage.Hash_SHA1(txtBoxEmpPass.Text);


                        connection.Open();
                        OleDbCommand command2 = new OleDbCommand();
                        command2.Connection = connection;
                        command2.CommandText = ("INSERT INTO Employee_login (Emp_ID, [Password]) VALUES(@emp_id, @password)");

                        command2.Parameters.AddWithValue("@emp_id", txtBoxEmp_ID.Text);
                        command2.Parameters.AddWithValue("@password", password);

                        command2.ExecuteNonQuery();
                        MessageBox.Show("password saved!");
                        connection.Close();
                        connection.Dispose();


                     

                    
                }
            }
            catch(Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
            finally
            {
                connection.Close();
            }
        }
    }
}
